## W1502 (boolean-datetime)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

Using `datetime.time` in a boolean context can hide subtle bugs when the time
they represent matches midnight UTC. This behaviour was fixed in Python 3.5.
See http://bugs.python.org/issue13936 for reference. It can't be emitted when using Python >= 3.5.



### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22boolean-datetime%22+OR+%22W1502%22)
